ports:
  - port: 8088
    onOpen: open-browser
tasks:
  - before: echo 'Setting up your development environment'
    init: npm install
    command: npm run develop
  - name: Autotesting
    command: npm test
    openMode: split-right
