ports:
  - port: 8088
    onOpen: open-browser
tasks:
  - before: echo 'Setting up your development environment'
    init: npm install
    command: cd ./src && echo -e 'Run the following command... \n\n\t\tnpm run develop' && npm run develop
  - name: Autotesting
    init: npm install
    command: npm test
    openMode: split-right
