ports:
  - port: 8088
    onOpen: open-browser
tasks:
  - before: echo 'Setting up your development environment'
    init: npm install
    command: echo -e '\n\n\n\n\nStarting the web server....\n\n\n\n\n' && npm run develop
  - name: Autotesting
    init: npm install
    command: npm test
    openMode: split-right
