ports:
  - port: 8088
    onOpen: open-browser
tasks:
  - before: echo 'Setting up your development environment'
    init: npm install
    command: cd ./src && echo '\n\n\n Run the following command... \n\n\t\tserve -l 8088'
  - name: Autotesting
    init: npm install
    command: npm test
    openMode: split-right
